# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e74aa9ce73e2d5bdb9d38b748f679aab8de56fff22051d9d8e2282c9a83a92924791bfb56f5162a64343f518dc5f5df441411f3d9d6c8236c56427ec59f1f649

test:
  secret_key_base: 6310251d1f71f51ece02122d5faab4998ebb059c920fcf9383ad264162b65c9cbf8295b23596da125120259bfdcf1d7eaa9738e4a1fe8f55668162f9829cd78e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
