# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242e9bbd1f842cde724d50ca684da10e5280078d87897c2aacc123aea8d8e563baf9dcb60abedfee123ef46a9ed6668f022152fae999a646b8ce92a0d87a210e

test:
  secret_key_base: 57582ffffdedb07df86f37d0366b83aa3d516e0c931bcbdf6078036118975027c3aa5f42ccca5b4dd36aa39d10c8b3d7a214a9c3da4c1922c3d7665aa91df21e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
